 CREATE TABLE drzava
    (
        drzava_id SERIAL,
        nazivDrzave VARCHAR(50) NOT NULL,
        PRIMARY KEY (drzava_id),
        UNIQUE (nazivDrzave)
    );

    CREATE TABLE mjesto
    (
        id SERIAL,
        postBr VARCHAR(20),
        nazMjesto VARCHAR(50),
        drzava_id INT NOT NULL,
        PRIMARY KEY (id),
        UNIQUE (postBr, nazMjesto),
        FOREIGN KEY (drzava_id) REFERENCES drzava(drzava_id)
    );

    CREATE TABLE korisnik
    (
        korisnik_id SERIAL,
        imeKorisnik VARCHAR(50) NOT NULL,
        prezimeKorisnik VARCHAR(50) NOT NULL,
        emailKorisnik VARCHAR(50) NOT NULL,
        telefonKorisnik VARCHAR(20) NOT NULL,
        ovlastKorisnik VARCHAR(20),
        mjesto_id INT NOT NULL,
        PRIMARY KEY (korisnik_id),
        UNIQUE (emailKorisnik),
        UNIQUE (telefonKorisnik),
        FOREIGN KEY (mjesto_id) REFERENCES mjesto(id)
    );

    CREATE TABLE rezervacija
    (
        rezervacija_id SERIAL,
        datumRezerviranja DATE NOT NULL DEFAULT CURRENT_DATE,
        placeno BOOLEAN NOT NULL DEFAULT FALSE,
        iznos_rezervacije NUMERIC(10,2) NOT NULL,
        korisnik_id INT NOT NULL,
        PRIMARY KEY (rezervacija_id),
        FOREIGN KEY (korisnik_id) REFERENCES korisnik(korisnik_id)
    );

    CREATE TABLE soba (
        soba_id SERIAL,
        broj_sobe VARCHAR(5) NOT NULL UNIQUE,
        kat INTEGER NOT NULL CHECK (kat BETWEEN 1 AND 4),
        vrsta VARCHAR(20) NOT NULL,
        cijena NUMERIC(10,2) NOT NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'DOSTUPNA',
        kapacitet INTEGER NOT NULL CHECK (kapacitet BETWEEN 2 AND 3),
        balkon BOOLEAN NOT NULL,
        pogled_na_more BOOLEAN NOT NULL DEFAULT FALSE,
        PRIMARY KEY (soba_id)
    );

    CREATE TABLE dodatniSadrzaj
    (
        dodatniSadrzaj_id SERIAL,
        vrstaDodatniSadrzaj VARCHAR(20) NOT NULL,
        statusDodatniSadrzaj VARCHAR(20) NOT NULL,
        cijena_sadrzaj NUMERIC(10,2) NOT NULL,
        PRIMARY KEY (dodatniSadrzaj_id)
    );

    CREATE TABLE recenzija
    (
        recenzija_id SERIAL,
        ocjenaRecenzija INT NOT NULL CHECK ( ocjenaRecenzija BETWEEN 1 AND 10 ),
        komentarRecenzija TEXT NOT NULL,
        datumRecenzija DATE NOT NULL DEFAULT CURRENT_DATE,
        korisnik_id INT NOT NULL,
        PRIMARY KEY (recenzija_id),
        FOREIGN KEY (korisnik_id) REFERENCES korisnik(korisnik_id)
    );

    CREATE TABLE rezervirajSadrzaj
    (
        rezervacija_id INT NOT NULL,
        dodatniSadrzaj_id INT NOT NULL,
        datum_sadrzaj DATE NOT NULL,
        PRIMARY KEY (rezervacija_id, dodatniSadrzaj_id, datum_sadrzaj),
        FOREIGN KEY (rezervacija_id) REFERENCES rezervacija(rezervacija_id),
        FOREIGN KEY (dodatniSadrzaj_id) REFERENCES dodatniSadrzaj(dodatniSadrzaj_id)
    );

    CREATE TABLE rezervirajSobu
    (
        rezervacija_id INT NOT NULL,
        soba_id INT NOT NULL,
        datumOdSoba DATE NOT NULL,
        datumDoSoba DATE NOT NULL,
        PRIMARY KEY (rezervacija_id, soba_id),
        FOREIGN KEY (rezervacija_id) REFERENCES rezervacija(rezervacija_id),
        FOREIGN KEY (soba_id) REFERENCES soba(soba_id),
        CHECK (datumDoSoba > datumOdSoba)
    );


 INSERT INTO drzava (nazivDrzave) VALUES
                                      ('Afghanistan'),
                                      ('Albania'),
                                      ('Algeria'),
                                      ('Andorra'),
                                      ('Angola'),
                                      ('Antigua and Barbuda'),
                                      ('Argentina'),
                                      ('Armenia'),
                                      ('Australia'),
                                      ('Austria'),
                                      ('Azerbaijan'),
                                      ('Bahamas'),
                                      ('Bahrain'),
                                      ('Bangladesh'),
                                      ('Barbados'),
                                      ('Belarus'),
                                      ('Belgium'),
                                      ('Belize'),
                                      ('Benin'),
                                      ('Bhutan'),
                                      ('Bolivia'),
                                      ('Bosnia and Herzegovina'),
                                      ('Botswana'),
                                      ('Brazil'),
                                      ('Brunei'),
                                      ('Bulgaria'),
                                      ('Burkina Faso'),
                                      ('Burundi'),
                                      ('Cabo Verde'),
                                      ('Cambodia'),
                                      ('Cameroon'),
                                      ('Canada'),
                                      ('Central African Republic'),
                                      ('Chad'),
                                      ('Chile'),
                                      ('China'),
                                      ('Colombia'),
                                      ('Comoros'),
                                      ('Congo'),
                                      ('Costa Rica'),
                                      ('Croatia'),
                                      ('Cuba'),
                                      ('Cyprus'),
                                      ('Czech Republic'),
                                      ('Denmark'),
                                      ('Djibouti'),
                                      ('Dominica'),
                                      ('Dominican Republic'),
                                      ('DR Congo'),
                                      ('East Timor'),
                                      ('Ecuador'),
                                      ('Egypt'),
                                      ('El Salvador'),
                                      ('Equatorial Guinea'),
                                      ('Eritrea'),
                                      ('Estonia'),
                                      ('Eswatini'),
                                      ('Ethiopia'),
                                      ('Fiji'),
                                      ('Finland'),
                                      ('France'),
                                      ('Gabon'),
                                      ('Gambia'),
                                      ('Georgia'),
                                      ('Germany'),
                                      ('Ghana'),
                                      ('Greece'),
                                      ('Grenada'),
                                      ('Guatemala'),
                                      ('Guinea'),
                                      ('Guinea-Bissau'),
                                      ('Guyana'),
                                      ('Haiti'),
                                      ('Honduras'),
                                      ('Hungary'),
                                      ('Iceland'),
                                      ('India'),
                                      ('Indonesia'),
                                      ('Iran'),
                                      ('Iraq'),
                                      ('Ireland'),
                                      ('Israel'),
                                      ('Italy'),
                                      ('Ivory Coast'),
                                      ('Jamaica'),
                                      ('Japan'),
                                      ('Jordan'),
                                      ('Kazakhstan'),
                                      ('Kenya'),
                                      ('Kiribati'),
                                      ('Kosovo'),
                                      ('Kuwait'),
                                      ('Kyrgyzstan'),
                                      ('Laos'),
                                      ('Latvia'),
                                      ('Lebanon'),
                                      ('Lesotho'),
                                      ('Liberia'),
                                      ('Libya'),
                                      ('Liechtenstein'),
                                      ('Lithuania'),
                                      ('Luxembourg'),
                                      ('Madagascar'),
                                      ('Malawi'),
                                      ('Malaysia'),
                                      ('Maldives'),
                                      ('Mali'),
                                      ('Malta'),
                                      ('Marshall Islands'),
                                      ('Mauritania'),
                                      ('Mauritius'),
                                      ('Mexico'),
                                      ('Micronesia'),
                                      ('Moldova'),
                                      ('Monaco'),
                                      ('Mongolia'),
                                      ('Montenegro'),
                                      ('Morocco'),
                                      ('Mozambique'),
                                      ('Myanmar'),
                                      ('Namibia'),
                                      ('Nauru'),
                                      ('Nepal'),
                                      ('Netherlands'),
                                      ('New Zealand'),
                                      ('Nicaragua'),
                                      ('Niger'),
                                      ('Nigeria'),
                                      ('North Korea'),
                                      ('North Macedonia'),
                                      ('Norway'),
                                      ('Oman'),
                                      ('Pakistan'),
                                      ('Palau'),
                                      ('Palestine'),
                                      ('Panama'),
                                      ('Papua New Guinea'),
                                      ('Paraguay'),
                                      ('Peru'),
                                      ('Philippines'),
                                      ('Poland'),
                                      ('Portugal'),
                                      ('Qatar'),
                                      ('Romania'),
                                      ('Russia'),
                                      ('Rwanda'),
                                      ('Saint Kitts and Nevis'),
                                      ('Saint Lucia'),
                                      ('Saint Vincent and the Grenadines'),
                                      ('Samoa'),
                                      ('San Marino'),
                                      ('Sao Tome and Principe'),
                                      ('Saudi Arabia'),
                                      ('Senegal'),
                                      ('Serbia'),
                                      ('Seychelles'),
                                      ('Sierra Leone'),
                                      ('Singapore'),
                                      ('Slovakia'),
                                      ('Slovenia'),
                                      ('Solomon Islands'),
                                      ('Somalia'),
                                      ('South Africa'),
                                      ('South Korea'),
                                      ('South Sudan'),
                                      ('Spain'),
                                      ('Sri Lanka'),
                                      ('Sudan'),
                                      ('Suriname'),
                                      ('Sweden'),
                                      ('Switzerland'),
                                      ('Syria'),
                                      ('Taiwan'),
                                      ('Tajikistan'),
                                      ('Tanzania'),
                                      ('Thailand'),
                                      ('Togo'),
                                      ('Tonga'),
                                      ('Trinidad and Tobago'),
                                      ('Tunisia'),
                                      ('Turkey'),
                                      ('Turkmenistan'),
                                      ('Tuvalu'),
                                      ('Uganda'),
                                      ('Ukraine'),
                                      ('United Arab Emirates'),
                                      ('United Kingdom'),
                                      ('United States'),
                                      ('Uruguay'),
                                      ('Uzbekistan'),
                                      ('Vanuatu'),
                                      ('Vatican City'),
                                      ('Venezuela'),
                                      ('Vietnam'),
                                      ('Yemen'),
                                      ('Zambia'),
                                      ('Zimbabwe');


 INSERT INTO dodatnisadrzaj (vrstaDodatniSadrzaj, statusDodatniSadrzaj, cijena_sadrzaj) VALUES
                                                                                            ('bazen', 'dostupan', 7.00),
                                                                                            ('restoran', 'dostupan', 10.00),
                                                                                            ('teretana', 'dostupan', 5.00);